name: Build Xiaomi Platina (A10)

on:
  workflow_dispatch:

env:
  DEVICE_NAME: "xiaomi_platina"
  DEVICE_CODENAME: "platina"

  CUSTOM_CMDS: "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS: "LD=ld.lld"

  KERNEL_SOURCE: "https://github.com/pix106/android_kernel_xiaomi_southwest-4.19.git"
  KERNEL_BRANCH: "main"

  CLANG_SOURCE: "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH: ""

  GCC_GNU: false

  DEFCONFIG_NAME: "platina_defconfig"
  BUILD_OTHER_CONFIG: false

  KERNELSU_AUTO_GET: "true"
  KERNELSU_AUTO_FORK: "resukisu"
  KERNELSU_METHOD: "shell"

  SUSFS_ENABLE: false

  DROIDSPACES_ENABLE: true

  HOOK_METHOD: "syscall"

  AK3_SOURCE: "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH: "master"

  PACK_METHOD: "Anykernel3"
  ROM_TEXT: "arrow_os_a10"

  PYTHON_VERSION: "3"
  NEED_DTBO: false
  GENERATE_DTB: false
  GENERATE_CHIP: "qcom"
  REKERNEL_ENABLE: false

jobs:
  build:
    name: Xiaomi Platina (A10)
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/build-env
      - uses: ./.github/workflows/build-ready
      - uses: ./.github/workflows/patch-no-kprobe
      - uses: ./.github/workflows/patch-droidspaces
      - uses: ./.github/workflows/build-process
      - uses: ./.github/workflows/pack-process
      - uses: ./.github/workflows/upload-files
